name: BUILD AND PUSH DAILYSPRINGPRACTICE IMAGE WORKFLOW
on: push
jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          ref: main
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '24'
      - name: Test
        run: ./gradlew test

  build_and_push_image:
    needs: test_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          ref: main
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dailyspringtest:latest .

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dailyspringtest:latest
